import type { Metadata } from "next";
import { Roboto_Condensed } from "next/font/google";
import "./globals.css";
import "./globalicons.css";
import Navigation from "@/samebook/ui/navigation/navigation";

const roboto = Roboto_Condensed({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        <div>
          <Navigation />
        </div>
        <div className="pt-[var(--header-height)] bg-background-primary min-h-screen">{children}</div>
      </body>
    </html>
  );
}
